apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs18-example
spec:
  ingressClassName: traefik
  rules:
    - host: hello-world.f1arcade.steadweb.com
      http:
        paths:
          - backend:
              service:
                name: nodejs18-example
                port:
                  number: 80
            path: /
            pathType: Prefix
